name = "PyRhodium"
uuid = "e525b322-f4d5-5e8a-9e4c-f31b6ef474ca"
version = "0.1.2-DEV"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
IterableTables = "1c8ee90f-4401-5389-894e-7a04a3dc0f4d"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
Conda = "1.3"
julia = "1"
DataFrames = "0.19, 0.20, 0.21"
DataStructures = "0.17, 0.18"
Distributions = "0.21, 0.22, 0.23"
PyPlot = "2.8"
PyCall = "1.91"
IterableTables = "1"

[targets]
test = ["Test", "Distributions", "DataFrames", "Roots"]
